# R script to test gamCopula bicoppd1d2 with family 301
# This will generate results to compare with Python implementation

library(gamCopula)

cat("=== Testing gamCopula family 301 ===\n")

# Load test data generated by Python
if (file.exists("test_data_for_r_comparison.csv")) {
  test_data <- read.csv("test_data_for_r_comparison.csv")
  cat("✓ Loaded test data:", nrow(test_data), "observations\n")
} else {
  # Generate same data as Python (same seed)
  set.seed(123)
  n <- 100
  u <- runif(n, 0.01, 0.99)
  v <- runif(n, 0.01, 0.99)
  test_data <- data.frame(u = u, v = v)
  write.csv(test_data, "test_data_for_r_comparison.csv", row.names = FALSE)
  cat("✓ Generated test data:", nrow(test_data), "observations\n")
}

# Load test parameters
if (file.exists("test_thetas_for_r_comparison.csv")) {
  theta_data <- read.csv("test_thetas_for_r_comparison.csv")
  test_thetas <- theta_data$theta
} else {
  test_thetas <- c(2.0, -1.5, 0.5, -0.8, 1.2, -2.0)
  write.csv(data.frame(theta = test_thetas), "test_thetas_for_r_comparison.csv", row.names = FALSE)
}

cat("✓ Test parameters:", length(test_thetas), "different theta values\n")
cat("  Thetas:", paste(test_thetas, collapse = ", "), "\n\n")

# Prepare data matrix for bicoppd1d2
y_matrix <- as.matrix(test_data[, c("u", "v")])

# Store results
all_results <- data.frame()

for (i in seq_along(test_thetas)) {
  theta <- test_thetas[i]
  cat("--- Testing theta =", theta, "---\n")
  
  # Determine expected behavior for family 301
  if (theta > 0) {
    cat("Expected: Standard Clayton (VineCopula family 3)\n")
  } else {
    cat("Expected: 90° rotated Clayton (VineCopula family 23)\n")
  }
  
  tryCatch({
    # Prepare input matrix for bicoppd1d2: [u, v, theta, par2]
    input_matrix <- cbind(y_matrix, theta, 0)
    
    # Call bicoppd1d2 with family 301
    # p=TRUE (PDF), d1=TRUE (1st derivative), d2=TRUE (2nd derivative)
    result <- bicoppd1d2(input_matrix, family = 301, p = TRUE, d1 = TRUE, d2 = TRUE)
    
    cat("✓ bicoppd1d2 computed successfully\n")
    cat("  Result dimensions:", dim(result), "\n")
    
    # Extract results (bicoppd1d2 returns matrix with rows: [pdf, d1, d2])
    if (nrow(result) >= 3) {
      pdf_vals <- result[1, ]
      d1_vals <- result[2, ]
      d2_vals <- result[3, ]
      
      # Convert PDF to log-PDF for comparison with Python
      logpdf_vals <- log(pdf_vals)
      
      cat("  PDF range: [", min(pdf_vals), ",", max(pdf_vals), "]\n")
      cat("  LogPDF range: [", min(logpdf_vals), ",", max(logpdf_vals), "]\n")
      cat("  D1 range: [", min(d1_vals), ",", max(d1_vals), "]\n")
      cat("  D2 range: [", min(d2_vals), ",", max(d2_vals), "]\n")
      
      # Check for issues
      pdf_finite <- sum(is.finite(pdf_vals))
      d1_finite <- sum(is.finite(d1_vals))
      d2_finite <- sum(is.finite(d2_vals))
      
      cat("  Finite values - PDF:", pdf_finite, "/", length(pdf_vals), "\n")
      cat("  Finite values - D1:", d1_finite, "/", length(d1_vals), "\n")
      cat("  Finite values - D2:", d2_finite, "/", length(d2_vals), "\n")
      
      # Store results
      for (j in seq_len(nrow(y_matrix))) {
        result_row <- data.frame(
          theta_index = i - 1,  # 0-based to match Python
          theta = theta,
          obs_index = j - 1,    # 0-based to match Python
          u = y_matrix[j, 1],
          v = y_matrix[j, 2],
          pdf = pdf_vals[j],
          logpdf = logpdf_vals[j],
          derivative_1st = d1_vals[j],
          derivative_2nd = d2_vals[j]
        )
        all_results <- rbind(all_results, result_row)
      }
      
    } else {
      cat("  ❌ Unexpected result dimensions\n")
    }
    
  }, error = function(e) {
    cat("  ❌ Error:", e$message, "\n")
  })
  
  cat("\n")
}

# Save results
output_file <- "r_gamcopula_301_results.csv"
write.csv(all_results, output_file, row.names = FALSE)
cat("✓ R gamCopula results saved to:", output_file, "\n")
cat("  Shape:", nrow(all_results), "x", ncol(all_results), "\n")
cat("  Columns:", paste(colnames(all_results), collapse = ", "), "\n")

# Summary statistics
cat("\n=== Summary Statistics ===\n")
if (nrow(all_results) > 0) {
  cat("Total observations:", nrow(all_results), "\n")
  cat("Unique theta values:", length(unique(all_results$theta)), "\n")
  
  # Check for problematic values
  pdf_issues <- sum(!is.finite(all_results$pdf))
  logpdf_issues <- sum(!is.finite(all_results$logpdf))
  d1_issues <- sum(!is.finite(all_results$derivative_1st))
  d2_issues <- sum(!is.finite(all_results$derivative_2nd))
  
  if (pdf_issues > 0 || logpdf_issues > 0 || d1_issues > 0 || d2_issues > 0) {
    cat("⚠️  Issues found:\n")
    cat("  Non-finite PDF:", pdf_issues, "\n")
    cat("  Non-finite LogPDF:", logpdf_issues, "\n")
    cat("  Non-finite D1:", d1_issues, "\n")
    cat("  Non-finite D2:", d2_issues, "\n")
  } else {
    cat("✓ All values are finite\n")
  }
}

cat("\n=== Comparison Instructions ===\n")
cat("1. Run the Python test script: python test_clayton_family_301.py\n")
cat("2. Compare files:\n")
cat("   - python_clayton_301_results.csv (Python results)\n")
cat("   - r_gamcopula_301_results.csv (R results)\n")
cat("3. Check that logpdf, derivative_1st, and derivative_2nd columns match\n")
cat("4. Family 301 should give identical results between Python and R\n")