name: Update Contributors

on:
  push: {}
  workflow_dispatch:

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Generate CONTRIBUTORS.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install requests
          python .github/scripts/contributors.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: '[AUTOMATED] update contributors list [skip ci]'
          title: 'Update contributors list'
          body: 'This PR updates the contributors list automatically.'
          branch: 'auto/update-contributors'
          add-paths: |
            README.md