name: Lint and Commit

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest 
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Configure git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13' 
    - name: Install ruff without running check or format
      uses: astral-sh/ruff-action@v3
      with:
          args: "--version"
          src: "./src"
    
    - name: Format (fix issues automatically)
      if: github.event.pull_request.head.repo.full_name == github.repository
      run: ruff check --fix .
    
    - name: Format code style
      if: github.event.pull_request.head.repo.full_name == github.repository
      run: ruff format
    
    - name: Commit changes
      if: github.event.pull_request.head.repo.full_name == github.repository
      uses: stefanzweifel/git-auto-commit-action@v6
      with:
        commit_message: '[AUTOMATED] Style fixes by ruff'
        file_pattern: '*.py'
        skip_fetch: false
        skip_checkout: false

    - name: Lint (fail if formatting is wrong)
      run: ruff check .